services:
  web:
    container_name: odoo
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    networks:
      - odoo-network
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb:
    container_name: bdd-odoo
    image: postgres:15
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  odoo-network: {}
volumes:
  db-data:
