---
galaxy_info:
  author: "Loic"
  description: "Rôle Ansible pour déployer ic_webapp avec Docker Compose"
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []